arm_controller/gains/elbow_joint/i: 10
arm_controller/gains/elbow_joint/d: 1 
arm_controller/gains/elbow_joint/p: 1000 
arm_controller/gains/shoulder_lift_joint/d: 10 
arm_controller/gains/shoulder_lift_joint/i: 1 
arm_controller/gains/shoulder_lift_joint/p: 1000 
arm_controller/gains/shoulder_pan_joint/d: 10 
arm_controller/gains/shoulder_pan_joint/i: 1 
arm_controller/gains/shoulder_pan_joint/p: 1000 
arm_controller/gains/wrist_1_joint/d: 10 
arm_controller/gains/wrist_1_joint/i: 1 
arm_controller/gains/wrist_1_joint/p: 1000 
arm_controller/gains/wrist_2_joint/d: 10 
arm_controller/gains/wrist_2_joint/i: 1 
arm_controller/gains/wrist_2_joint/p: 1000
arm_controller/gains/wrist_3_joint/d: 10 
arm_controller/gains/wrist_3_joint/i: 1 
arm_controller/gains/wrist_3_joint/p: 1000 

/ddynrec/robot___elbow_joint___damping: 25.0
/ddynrec/robot___elbow_joint___friction: 25.0
/ddynrec/robot___shoulder_lift_joint___damping: 25.0
/ddynrec/robot___shoulder_lift_joint___friction: 25.0
/ddynrec/robot___shoulder_pan_joint___damping: 25.0
/ddynrec/robot___shoulder_pan_joint___friction: 25.0
/ddynrec/robot___world_joint___damping: 25.0
/ddynrec/robot___world_joint___friction: 25.0
/ddynrec/robot___wrist_1_joint___damping: 25.0
/ddynrec/robot___wrist_1_joint___friction: 25.0
/ddynrec/robot___wrist_2_joint___damping: 25.0
/ddynrec/robot___wrist_2_joint___friction: 25.0
/ddynrec/robot___wrist_3_joint___damping: 25.0
/ddynrec/robot___wrist_3_joint___friction: 25.0